export default {
	site: "http://localhost:5002",
	scanner: {
		dynamicSampling: false, // Evita que agrupe las páginas del blog o ciudades
	},
	urls: [
		"/",
		"/servicios/",
		"/servicios/desarrollo-web/",
		"/servicios/branding/",
		"/servicios/marketing-redes/",
		"/servicios/automatizacion/",
		"/servicios/rediseno-marca/",
		"/servicios/tienda-en-linea/",
		"/digitalizamos/",
		"/digitalizamos/ciudad-de-mexico/",
		"/digitalizamos/guadalajara/",
		"/digitalizamos/monterrey/",
		"/digitalizamos/puebla/",
		"/digitalizamos/queretaro/",
		"/digitalizamos/estado-de-mexico/",
		"/digitalizamos/merida/",
		"/digitalizamos/tijuana/",
		"/digitalizamos/hidalgo/",
		"/digitalizamos/quintana-roo/",
		"/digitalizamos/canada/",
		"/blog/",
		"/blog/top-agencias-diseno-web-b2b-mexico/",
		"/blog/costo-real-pagina-web-barata/",
		"/blog/plantillas-devaluan-marca-b2b/",
		"/blog/diseno-minimalista-firmas-legales/",
		"/blog/branding-autoridad-empresas-b2b/",
		"/blog/automatizacion-agendas-redes-sociales/",
		"/blog/seo-b2b-mexico-vs-extranjeras/",
		"/blog/sede-digital-vs-sitio-web/",
		"/blog/agencia-digital-empresas-industriales/",
		"/blog/error-narrativa-sitios-corporativos/",
		"/blog/diseno-web-despachos-juridicos/",
		"/blog/funnel-linkedin-cierre-b2b/",
		"/blog/identidad-visual-constructoras/",
		"/blog/roi-desarrollo-medida-vs-wordpress/",
		"/blog/agencias-offshore-vs-koda/",
		"/sobre-nosotros/",
	],
};
